# Generated by Django 3.2.6 on 2021-12-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antenne',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Antenne')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
            ],
        ),
    ]
