# Generated by Django 3.2.6 on 2021-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='The event name')),
                ('location', models.CharField(max_length=150, verbose_name='Place')),
                ('date', models.DateField(verbose_name='Date of the event')),
                ('program', models.CharField(max_length=150, verbose_name='program of the event')),
                ('participant', models.ManyToManyField(to='member.Member')),
            ],
        ),
    ]
